---
title: "TROPICAL-REPO"
description: |
  Reproducible workflows for the study ....
author:
  - name: "Noelle Lucey"
    url: https://github.com/yihui
    affiliation: Smithsonian Tropical Research Institute
    affiliation_url: https://stri.si.edu/
  - name: "Jarrod J Scott"
    url: https://github.com/rich-iannone
    affiliation: Smithsonian Tropical Research Institute
    affiliation_url: https://stri.si.edu/
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```

This website provides reproducible workflows for our study on  .... We go through the steps  used to process .... We describe the various tools used to analyze and interpret the data. We also provide access to all data, data products, and code. With this workflow you can generate the figures and tables from the paper as well as many additional data products.

The workflow is mainly written in [R Markdown](https://rmarkdown.rstudio.com/) meaning that it contains a mixture of Markdown text and R code. Anyone should be able to reproduce our results with just this workflow and the [raw data](data-availability.html).

### Using this Site

The navigation bar at the top contains links to workflows, data/data products, supplementary material from the paper (see SOM), and a variety of other useful information. The site itself has many dynamic components. For example, you can sort and scroll through most of the tables, tabular data can be download in different formats, and several figures expand when clicked. All figures and tables from the final publication are included in the workflow.

On the bottom of each page you can find a link to the page's source code or visit the main GitHub repo for the site, also linked at the bottom of each page. Should you find any problems, there is a link to the issue page of the source repository. References are also included as are DOI links to the publications where applicable.

## Acknowledgements {.appendix}

Many of the computations were conducted on the Smithsonian High-Performance Cluster (SI/HPC), Smithsonian Institution. [doi:10.25572/SIHPC](https://doi.org/10.25572/SIHPC).

## Author Contributions {.appendix}


## Source Code {.appendix}

The source code for this page can be accessed on GitHub by [clicking this link](https://github.com/tropical-repo/web/blob/master/index.Rmd).

## An Apology from JJS {.appendix}

Unfortunately, some of the publications we cite in this project sit behind paywalls. These papers are inaccessible unless you are at an institution that subscribes to the journal, you pay a crazy amount of money per article, or you obtain the article via "illegal" means. Either way, at the moment this is beyond our control and hence I apologize if you are unable to access some of the article we cite. 
